-- ─────────────────────────────────────────────────────────────
-- ANOTHER NPC SHOP — Esquema Inicial de Base de Datos para PostgreSQL
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS productos (
    id VARCHAR(10) PRIMARY KEY,
    meta_id VARCHAR(50),
    nombre VARCHAR(255) NOT NULL,
    precio DECIMAL(10, 2) NOT NULL,
    categoria VARCHAR(100),
    genero VARCHAR(50),
    marca VARCHAR(100),
    tallas TEXT[], -- Array de texto en PostgreSQL
    imagen VARCHAR(255),
    descripcion TEXT,
    disponible BOOLEAN DEFAULT TRUE
);

TRUNCATE TABLE productos;

INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('001', '25505323189139394', 'CAMISA MANGA CORTA RAYAS STWD', 8.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/001.jpg', 'S', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('002', '25196209210080357', 'TOP TIRANTES SOLES', 2.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/002.jpg', 'Xs', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('003', '25844431951912701', 'TOP TIRANTES SOL', 3.89, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/003.jpg', 'S', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('004', '25424788433865795', 'CAMISETA GRUESA 2.0 DE CALIDAD SUPERIOR', 16.99, 'sin_categoria', 'hombre', 'Abercrombie', ARRAY['S','M','L']::TEXT[], '/images/004.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('005', '25550630044633664', 'CAMISETA GRUESA PREMIUM HANLEY 2.0 CON ICONO EXCLUSIVO', 19.99, 'sin_categoria', 'hombre', 'Abercrombie', ARRAY['S','M','L']::TEXT[], '/images/005.jpg', 'S, Marrón', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('006', '25799504339743746', 'CAMISETA GRUESA PREMIUM CON MICROLOGO', 19.99, 'sin_categoria', 'hombre', 'Abercrombie', ARRAY['S','M','L']::TEXT[], '/images/006.jpg', 'L, Blanco', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('007', '25965854363081895', 'CAMISETA GRUESA PREMIUM CON MICROLOGO', 12.99, 'sin_categoria', 'hombre', 'Abercrombie', ARRAY['S','M','L']::TEXT[], '/images/007.jpg', 'L, Azul', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('008', '26198244456529366', 'SUDADERA DE FELPA CON CAPUCHA E ICONO FRENCH TERRY', 24.99, 'sin_categoria', 'hombre', 'Abercrombie', ARRAY['S','M','L']::TEXT[], '/images/008.jpg', 'S, Negro', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('009', '26350526831238940', 'POLO CON ICONO INSIGNIA DON''T SWEAT IT', 22.99, 'sin_categoria', 'hombre', 'Abercrombie', ARRAY['S','M','L']::TEXT[], '/images/009.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('010', '26588206910803008', 'SUDADERA DE FELPA CON CAPUCHA E ICONO FRENCH TERRY', 24.99, 'sin_categoria', 'hombre', 'Abercrombie', ARRAY['S','M','L']::TEXT[], '/images/010.jpg', 'XS, Zafiro', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('011', '26783752317892712', 'TANK TOP PRIMAVERA SOUND X PB', 4.79, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/011.jpg', 'M', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('012', '25577957235195997', 'CAMISETA GRIS ÁNGELES', 3.89, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/012.jpg', 'S', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('013', '25655944737406805', 'CAMISETA HONDA CIVIC', 5.39, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/013.jpg', 'M', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('014', '34372832325648788', 'CROP TOP TIRANTES', 2.09, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/014.jpg', 'M', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('015', '25632738873051606', 'CAMISETA BOXY', 3.89, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/015.jpg', 'xl', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('016', '25750463141306743', 'POLO MANGA CORTA', 4.79, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/016.jpg', 'M', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('017', '33544768795167751', 'CAMISETA GRAFICO', 3.89, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/017.jpg', 'M', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('018', '33363834529931285', 'TOP HALTER ESPALDA DESCUBIERTA', 3.89, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/018.jpg', 'L', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('019', '26279780898294371', 'CAMISETA SIN MANGAS LAVADA', 2.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/019.jpg', 'S', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('020', '26276314985308721', 'CAMISA MANGA CORTA RAYAS STWD', 17.98, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/020.jpg', 'M', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('021', '25023273517345942', 'CAMISETA ALGODÓN MANGA CORTA', 7.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/021.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('022', '25525829207073436', 'CAMISETA DE ALGODÓN LOGO', 6.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/022.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('023', '25534260112943373', 'CAMISETA DE ALGODÓN LOGO', 6.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/023.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('024', '25555063860781931', 'VESTIDO HALTER ESTAMPADO PALMERAS', 9.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/024.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('025', '25664951696494528', 'CAMISETA DE RAYAS LOGO', 6.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/025.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('026', '25665412729784110', 'TOP ENTALLADO TIRANTE ANCHOS', 7.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/026.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('027', '25757383887204557', 'CAMISETA ALGODÓN ESTAMPADA', 7.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/027.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('028', '25905486475806885', 'TARJETERO ESTAMPADO LOGO', 5.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/028.jpg', 'Talla unica', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('029', '26155621380697173', 'CAMISETA ALGODÓN ESTAMPADA', 7.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/029.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('030', '26596835939903079', 'TOP ENTALLADOO CREMALLERA', 9.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/030.jpg', 'pendiente', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('031', '26799701199629971', 'CAMISETA DE ALGODÓN LOGO', 6.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/031.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('032', '26811447431779090', 'TOP ENTALLADO TIRANTES ANCHOS', 7.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/032.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('033', '33611164505165989', 'TOP ABERTURA ESPALDA', 5.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/033.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('034', '33720476790931350', 'TOP ASIMÉTRICO RIBETE CONTRASTE', 7.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/034.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('035', '33971599565771971', 'CAMISETA HOMBRERAS MANGA CORTA', 7.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/035.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('036', '34097045156553516', 'CAMISETA DE ALGODÓN LOGO', 6.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/036.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('037', '25435934449439316', 'VESTIDO CORTO HALTER', 5.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/037.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('038', '25474787365527035', 'VESTIDO TERCIOPELO CUELLO ESCOTADO', 6.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/038.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('039', '25481784458160372', 'CHALECO TERCIOPELO CROP', 4.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/039.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('040', '25561087733561037', 'CAMISETA ALGODÓN ESTAMPADO', 5.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/040.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('041', '25564059546596405', 'VESTIDO TIRANTES PUNTO', 3.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/041.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('042', '25605151559140140', 'CAMISETA ALGODÓN LOGO', 4.49, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/042.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('043', '25609021748793371', 'BLUSA LENTEJUELAS HOMBROS DESCUBIERTOS', 6.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/043.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('044', '25622553320738963', 'PASADOR LAZO BORDADO', 1.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/044.jpg', 'Talla unica', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('045', '25817166254586006', 'VESTIDO MIDI DETALLE DRAPEADO', 4.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/045.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('046', '25908666012101512', 'TOP SATINADO TIRANTES FINOS', 6.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/046.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('047', '25917756987819223', 'TOP FRUNCIDO PALABRA DE HONOR', 6.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/047.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('048', '25931697119797925', 'CAMISETA CROP RAYAS', 3.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/048.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('049', '26044964881808129', 'TOP SATINADO TIRANTES FINOS', 6.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/049.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('050', '26143200852035266', 'VESTIDO FORRO CORTO PALABRA DE HONOR', 5.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/050.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('051', '26380574861591546', 'FUNDA PORTÁTIL LOGO', 3.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/051.jpg', 'Talla unica', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('052', '26416294184638953', 'TOP PUNTO DETALLES CONTRASTE', 7.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/052.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('053', '26426315570305196', 'CAMISETA ALGODÓN MENSAJE ESTAMPADO', 5.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/053.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('054', '33334067559575261', 'TOP BANDEAU RAYAS', 3.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/054.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('055', '33933671879564375', 'CAMISA CROP RAYAS', 6.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/055.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('056', '34010935948520240', 'VESTIDO ASIMÉTRICO STRASS', 3.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/056.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('057', '34413606118238049', 'TOP TERCIOPELO ASIMÉTRICO STRASS', 2.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/057.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('058', '34642104878722178', 'VESTIDO PUNTO CORTO', 3.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/058.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('059', '34713987794867198', 'CAMISA RAYAS TEXTURA', 5.99, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/059.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('060', '25545259995132401', 'CAMISETA DOBLE EL JUEGO DEL CALAMAR', 7.79, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/060.jpg', 'M', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('061', '25884631481167321', 'CAMISETA HONDA CIVIC', 5.39, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/061.jpg', 'S', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('062', '25667704766172587', 'CAMISETA VERDE TEXTO', 3.89, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/062.jpg', 'S', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('063', '25672186162410693', 'CAMISETA POLIAMIDA MANGA CORTA', 2.69, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/063.jpg', 'L', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('064', '25488213340801568', 'FUNDA IPHONE ACOLCHADA STWD', 2.39, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/064.jpg', '14 Pro', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('065', '26324815610456371', 'CAMISA MANGA CORTA CORTA RAYAS STWD', 15.58, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/065.jpg', 'L', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('066', '25580692341631535', 'CAMISETA MANGA CORTA ESTRUCTURADA', 11.67, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/066.jpg', 'S', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('067', '26018417797791930', 'CAMISETA HEAVY WEIGHT', 7.78, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/067.jpg', 'M', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('068', '25645315658450664', 'CROP TOP TIRANTES', 2.09, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/068.jpg', 'S', FALSE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('069', '24195538580144023', 'CAMISETA VARSITY 50TH ANNIVERSARY', 4.78, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/069.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('070', '24951030314573901', 'CAMISETA EFECTO LAVADO CARE BEARS', 5.38, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/070.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('071', '25202028322808901', 'CAMISETA FLOR VOLUMEN', 5.98, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/071.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('072', '25409450852084008', 'VESTIDO SARGA CRUZADO', 8.39, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/072.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('073', '25446699838364692', 'TOP FORNITURA PICUETA', 4.78, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/073.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('074', '25447373358275345', 'CAMISETA FLOR VOLUMEN', 5.98, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/074.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('075', '25717898661206744', 'CAMISA FLUIDA BOLSILLO', 6.88, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/075.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('076', '25735006256163884', 'VESTIDO PALABRA DE HONOR', 8.39, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/076.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('077', '25739947929002932', 'CAMISETA VARSITY 50TH ANNIVERSARY', 4.78, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/077.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('078', '25773706742238551', 'CAMISETA EFECTO LAVADO TEXAS', 4.78, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/078.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('079', '25822548267410345', 'CAMISA CROP POPELÍN', 5.98, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/079.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('080', '25923594183930244', 'CAMISETA TEXTO BORDADO', 4.78, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/080.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('081', '25944715865216782', 'TOP TEXTURA VOLANTES', 3.88, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/081.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('082', '25983928951295012', 'CAMISA MANGA CORTA LAZOS CON RAMO', 5.19, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/082.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('083', '26010962778593222', 'CAMISETA VARSITY 50TH ANNIVERSARY', 4.78, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/083.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('084', '26146619531636891', 'TOP LAZOS', 5.98, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/084.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('085', '26200334492893656', 'TOP PALABRA DE HONOR LAZO', 5.98, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/085.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('086', '26212973234987572', 'TOP ASIMÉTRICO FRUNCES', 5.38, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/086.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('087', '26389320907332139', 'CAMISETA VARSITY 50TH ANNIVERSARY', 4.78, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/087.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('088', '26665024256418930', 'TOP CAPA VOLANTES', 5.38, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/088.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('089', '26829500296750016', 'CAMISETA HEAVY COTTON', 5.98, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/089.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('090', '34110915441855058', 'CAMISA CROP POPELÍN', 11.96, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/090.jpg', 'M', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('091', '34124740567139714', 'CAMISETA RIB', 5.96, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/091.jpg', 'S', TRUE);
INSERT INTO productos (id, meta_id, nombre, precio, categoria, genero, marca, tallas, imagen, descripcion, disponible) VALUES ('092', '34539317332382693', 'CAMISETA MANGA VOLANTES', 3.88, 'sin_categoria', 'mujer', '', ARRAY['S','M','L']::TEXT[], '/images/092.jpg', 'M', TRUE);